### PR TITLE
Technical skills groups

### PR DESCRIPTION
**Pull request by jonathf**
User will no longer have the opertunity to choose freely how the tech-skill section is made:

* Skill has to be selected from a predifined list (located at `templates/tech_skills.toml`).
* Skill group is automatically determined by internal algorithm.

This is a work in progress, but I foresee the tech-list itself being the subject to a bit of discussion,
so I am posting it early so everyone that cares can have a look.

Things that can be reviewed per now:

* Does the list of skills look okay?
* Does the list of allowed groups look okay?
* Currently, some of the label names are too long for the document output.
  We either need to shorten them, or do something with the output format.
* The smart-grouper functions needs a lower threshold for the number skills a group should preferrably have.
* The algorithm also need to know what to do with leftovers if it fails. Should they be discarded, or should we have small groups?

Things I think is missing in this PR:
* [x] test: ensure all group labels in skill also exists in allowed_labels.
* [x] test: ensure all icons have an associated skill.
* [x] Updated parser to show valid skills with indicator for badges.
* [x] updated documentation to say something about adding new skills.
* [x] Make sure that all CVs in internal/cv looks okay.
* [x] Add group sorting of the groups according to allowed_labels.

### CODE REVIEW

**Comment by jonathf** [comment]
Here are three renders with defaults set to minimum of 5 skills and cutting enabled for a few of our CVs:

2021-06-13-205410_2160x1350_scrot
2021-06-13-205200_2160x1350_scrot
2021-06-13-204446_2160x1350_scrot
2021-06-13-204222_2160x1350_scrot

I think the allocation of groups works as intended, the list of skills looks really good, but the left-hand-side label name don't. I think we might need to either shorten the names, shrink the font, or increase the left-hand space.

**Comment by kememil** [comment]
Nice!
The tech-list is indeed extensive, but is a huge improvement wrt aggregation from when everybody writes the same skill in different ways. It is also non-exhaustive, so it should be possible for users to add new items and map them to appropriate groups when needed. I think you have made a great job so far. If you want a second opinion on the group-skill mapping I can take a more detailed look at it.

The left-hand-side labels are truly not looking good and it is difficult to see where one ends and the next starts. One possible solution, in addition to the ones mentioned, is to add a horizontal separator between them, and adjust/center the skills within each group vertically.

**Comment by jonathf** [comment]
Thanks.

Yeah, it is a bit extensive. If you see the `tech_skills.toml` file you will see that there is also the beginning of a `short_map` many-to-one mapping, making aggregation a lot better.

The list is also designed to be complete in the sense that I have not made any (significant) judgement calls of what to include. But perhaps that would be a good idea? IDK, it would definetly create some rumbling.

Yes, more eyes on the group skills and labels is much appriciated.

Horizontal seperator is a good idea:
2021-06-14-150231_2160x1350_scrot
A lot better, but I still think we need ot choose shorten the name of e.g. "High performance computing".

**Comment by mandus** [comment]
Personally I'm not sold on all this small icons you put in here - looks busy to me. And things like "C C" (where one of them is an icon) seems redundant.

**Comment by jonathf** [comment]
Fair enough. I can definetly remove the one for C, and make the whole thing optional. Or remove it for that matter, as it is a tiny feature.

That said, this PR is not related to the icons, but reducing the freedom of tech skill choices to a predefined list, and the automatic allocation of skill groups. It is what is required to deal with the issue outlined in #50.

**Comment by jonathf** [comment]
All components of the feature is now added.

In addition as discussed with Åsmund:
* badges is now optional and default to be off.
* The badge for C is removed.

**Pull request merged**
