### PR TITLE
Refactor to allow for other non-latex targets

### PR DESCRIPTION
**Pull request by jonathf**
Here is a small work-in-progress for what we can do with aggregation.

Basically, one needs a master content toml file. Currently only two variables are defined:
```
summary = "Some text in the beginning"
technical_skills = ["Python", "AWS", "C++"]
```
The former is normal text insertion, while the latter is a filter defiing which skills to include.

With it, we can make a document from mulitple normal content toml like this:

```
cv aggregate agg.toml internal/cv/*/content.toml
```
The output is `agg.pdf` and looks like this:
2021-08-11-142316_2160x1350_scrot

### CODE REVIEW

**Comment by jonathf** [comment]
@kememil, @mandus,
right now I am looking into what the aggregate document should look like in the end, like tables, titles, document structure etc.

Can one or both of you formulate something on what you want to see? Or PM me something specific, if we have examples at hand?

**Comment by kememil** [comment]
I think of this as a means to extract a type of fact sheet about XAL and its employees. I like the counter for the different tech skills and think we could do similar for number of PhDs, MScs, years of experience since graduation, value created in projects, etc. This can then be used in presentations like the one attached.
Expert Analytics Pitch - Master

**Comment by jonathf** [comment]
That should be doable.

So are you thinking we make a tex/pdf target that makes that slide, or is it enough that I make a csv target that lists all those details? The latter is obviously a bit simpler here.

**Comment by kememil** [comment]
I guess there is no use in generating the aggregated numbers if no-one knows where to find them (or that they even exist). Could this be linked to the "about us" section of xal.no? Ref. the long discussion in slack on combining CVs and website info.

**Comment by jonathf** [comment]
If cvcreator is used to create content to the website, then adding this stats to the output is trivial. :)

I'll focus on making a CSV output for now, and we can update it later.

**Comment by kememil** [comment]
Sounds good :)

**Comment by jonathf** [comment]
@kememil, adding most of the stuff you are mentioning require that we formalize the format for date, education, etc in the toml spec. It is not big, but it will require that we make minor edits to the toml specification.

I suggest we merge this now as it includes a refactoring (to seperate vitae from aggregate) that I rather build directly on in seperate PRs.

**Comment by jonathf** [comment]
Current status is that we can create this (with filters to shorten the number of skills and educations):
```csv
feature,value
num_employee,29
num_doctors,21
num_nationalities,4
num_languages_spoken,15
num_universities_attended,18
edu:Mathematics,9
edu:Physics,17
tech:AWS,8
tech:C++,22
tech:Python,29
```
This is good, but I think the following needs to be addressed:
* Number of nationalities is too low. I imagine this is from the lack of reporting. Should we require that the field being filled out?
* Anything related to years in research and number of research institutions is severly limited by the fact that postdocs are reported as work. Should we perhaps move postdocs over to education?
* I believe stats related to how long each employee have been working as a consultant is also relevant. To get that we should add a field for reporting the time one started working at the company?

**Comment by mandus** [comment]
Reporting postdoc as education rather than work is mostly counterproductive. In particular for new employees we need to push postdoc-time and really phd-time as well as prior work, not just education, since "education" tend to not count as experience. This depends of course to a large degree on the client, but I still will prefer that we keep postdoc in work experience.

**Comment by mandus** [comment]
regarding nationality, maybe we have used some historic information when we came up with the number in the slide, while the CV will just state what the current passport is saying. For some that may not be the same thing. This is just a guess on one contributing factor. I think the CV should state the current nationality if to be included - and I'm open to discuss if that field at all should be included in the CVs we are sending out.

**Comment by jonathf** [comment]
I think removing the nationality from the CV is a good idea. Keeping it in the toml however is a different conversation as we also create stats on them.

For the education part, I think we can make an upgrade.
We make a new field: Research. CV creator will determine based on if the size of the list if Research should be either merged into Work, merged into Education, or made into its own category.

**Comment by jonathf** [comment]
Hey @mandus, I think we should look into merging this now.

Current state of features:
* Enforce a bunch of features are written correctly: Format of birthdate, nationality, country (university), languages, language skill.
* Vitae and Aggregate is refactored into their own submodules. 
* TOML section: `[[education]]` is split into parts. Roughly it can now be described as (from `example.toml`):
```toml
[[education]]
start = 2012  # Optional
end = 2015

# The degree you achieved.
# Choices: Bachelor's degree | Master's degree | PhD | Diploma degree | Cand. Scient | Doctor Scient
degree = "Bachelor's degree"

# What the education will be sorted under.
# Choices: Mathematics | Physics | Scientific Computing | Mechanics | Engineering | Chemistry | Geology/Geophysics | Computer Science
topic = "Mathematics"

# Free form degree title
specialization = "Applied Mathematics"  # -> "Bachelor's degree in Applied Mathematics"

thesis_title = "My awesome dissertation!"  # Optional

department = "Department of Mathematics"  # Optional

# Required when degree is included:
university = "University of Oslo"
country = "Norway"
```

All the CVs are also updated to abide these new rules and should be merge at about the same time:
https://github.com/expertanalytics/internal/pull/167

**Pull request merged**
