### PR TITLE
Add in tight design features

### PR DESCRIPTION
**Pull request by jonathf**
Another set of opinionated updates:

* There is a lot of content where we use spacing as a delimiter.
  Using vertical bars instead allows for a more compact design while
  still being readable.
* Left column changes: smaller and right aligned.

Example: [feinberg3.pdf](https://github.com/expertanalytics/cvcreator/files/6554730/feinberg3.pdf)

### CODE REVIEW

**Comment by kememil** [comment]
I like the horizontal delimiter lines, but my impression is that the vertical bars in Technical skills are a bit messy.
As for the smaller text size in the left column, I think readability and the overall impression is better with same sized text in the left and right column.

**Comment by jonathf** [comment]
Thank you for you feedback @kememil!

The left side text size: fair enough. I'll change it back.

The vertical bar seperators:
I have made a feature where specific keywords trigger the inclusion of an appropriate icon prefix. The vertical bars is something I think makes more sense in that context. However since I kind of did the mistake here an releasing only the bar-part here, and the feature in question now is complete, I am expanding this PR to include the new feature as well.

## Tech-skill icons

It will look like this: [feinberg4.pdf](https://github.com/expertanalytics/cvcreator/files/6568850/feinberg4.pdf)

There is an icon folder, which we can add lots of dev-icons to. I've found many CC0 icons out there (which allows comerical usage), and adding is super easy.
I intend to add CLI tools for listing valid keywords, and docs for describing how to add your own later.

Obviously we can not support everything, as not everything has an icon (as the example shows), but I think it is cool even partially filled out, and a good fit for a nerdy company like us.

A nice side effect of this, is that it kind of forces tech skills to converge organically as each icon only trigger if the right name and spelling is entered.

**Comment by kememil** [comment]
Very nice :) I like the icons and agree that we don't need an exhausting list. A convergence on spelling would be a huge improvement :smile:

**Review by kememil — APPROVED** [review]
Looks good.

**Pull request merged**
