### PR TITLE
Add tech skills: Cufflinks and ROOT

### PR DESCRIPTION
**Pull request by krissbec**

### CODE REVIEW

**Comment by jonathf** [comment]
Looks like you removed all addition to the repo between 1.0.4 and 1.0.5. Do you mind adding them back?

Please also bump the version number to 1.0.6 in pyproject.toml so we can make a release.

Otherwise: Welcome to the XAL!

**Comment by krissbec** [comment]
Oops! Sorry, I had an old .toml file. It should be fixed now.

**Comment by jonathf** [comment]
No problem. :)

**Comment by jonathf** [comment]
New tag is in the pipeline and should be available within 5 minutes.

**Pull request merged**
