### PR TITLE
Refactor cvcreator

### PR DESCRIPTION
**Pull request by alexanfl**

### CODE REVIEW

**Comment by alexanfl** [comment]
These changes look good to me, how about you @gmkvaal ? @aless80 has also been doing some fixes lately, so might need to merge and resolve with them, @Cyangray .

**Comment by alexanfl** [comment]
@gmkvaal kan du godkjenne?

**Review by gmkvaal — COMMENTED** [review]
Vi prøver!

**Comment by alexanfl** [comment]
> Vi prøver!

Får ikke merget:(

**Review by gmkvaal — APPROVED** [review]

**Pull request merged**
