### PR TITLE
Updating the CLI to use subparsers

### PR DESCRIPTION
**Pull request by jonathf**
Current parser is doing to much. I've split it into a sub-parser system:
```
badges     List technical skill badges
create     Create CV as .pdf file
example    Create example .toml file
latex      Create CV as .tex file
txt2yaml   Convert old .txt to .yaml
yaml2toml  Convert old .yaml to .toml
```
Though this can be done with argparse, argparse is inconvenient and clunky, so I replaced it with a more modern framework: [click](https://github.com/pallets/click/)

Main interface renamed: `cvcreate -> cv`. This is save some typing and because `cvcreate create` look ridiculous. I've kept the parser `cvcreate` as an alias to `cv create` for those who want that.

Along the way:
* Refactored some of the content of `__main__.py` into other file.
* Update the README with all the new stuff so far.
* Move work experience higher up in CV template (as suggested by @gmkvaal).
* Added a new `example.toml` and a jpg output for README.
* Cleared out the old example folder.
* Added color to latex compiling messages not created by mklatex/pdflatex so it becomes easier to spot.

### CODE REVIEW

**Comment by mandus** [comment]
Click seems to be based on a very different style of coding - a lot moved to decorators instead of "regular" python-code. I'm fine with that if click is becoming "the standard way", but I've never seen it or heard about it before so I can't really judge. The only concern I have is that we should try to be relatively mainstream-python such that everyone in xal feel they can contribute to this project if the want. 

So; from my personal point of view, this update looks okay - but I will appreciate if a couple of the other significant contributors to the tool also have a look!

**Comment by alexanfl** [comment]
@mandus Could be positive that people learn how to use decorators in a relatively simple "environment" like this? If people are going to work with web frameworks like Flask, Django or FastAPI, they will have to learn about them anyway. Other than that, Click looked interesting.

**Comment by jonathf** [comment]
I have felt the pain of using the built-in argparse library beyond the vary simple. It is often becomes un-wieldy and has weird edge-cases that causes pain.

But I am not married to Click though. We could for example switch to e.g. [Python fire](https://github.com/google/python-fire) which is more "Pythonic" in this regard and equally popular.

**Comment by jonathf** [comment]
Irrespectively it is not much code in this since it is a tiny project. If someone how want to learn something about parsing, and want to use something else, it isn't too complicate to replace the whole thing. And I doubt that is going to change any time soon.

I'm merging this and moving on.

**Pull request merged**
