### PR TITLE
Use pipenv + extra needed dependency

### PR DESCRIPTION
**Pull request by stianlagstad**
Please feel free to reject this!:)

I'm not a tex-expert, so not sure why that extra dependency was needed. Using pipenv is nice, though. Let's you easily work in a virtual environment (no need to install cvcreate or any of the dependencies directly on the system).

### CODE REVIEW

**Comment by jonathf** [comment]
No worries. I am a fan of pipenv, but you will find opponents in our company.

**Comment by mandus** [comment]
@jonathf have your later PRs made this PR obsolete?

**Comment by jonathf** [comment]
No, not really. pipenv is for dev work, pypi is for deployment.

I'd reformulate the readme to reflect that though before merging.

@stianlagstad, you fix?

**Comment by mandus** [comment]
@jonathf does CI fail here due to missing merge with master? (sounds reasonable since @stianlagstad did work on a fork..) Should we just merge this, or is further updates needed?

**Comment by stianlagstad** [comment]
@mandus That was my thought initially, so I merged in master (in this commit: https://github.com/expertanalytics/cvcreator/pull/4/commits/98af69bbade4837f6c99f5013b16a29dd7a0a5eb). Still got the ci failure though. @jonathf: Can you take a look?

**Comment by jonathf** [comment]
ci is failing because ci isn't configured yet. But it is activated as we are about to add it.

Ignore the error for now.

**Pull request merged**
